<?php
/**
 *
 *
 * @author Sam Schmidt <samuel@dersam.net>
 * @since 2016-02-11
 */

namespace Dersam\RequestTracker\Action;

use Dersam\RequestTracker\Action;

class SearchTickets extends Action
{
    protected $endpoint = "/search/ticket?";
    protected $requiredParameters = ['id'];
    protected $defaults = [];

    public function getEndpoint()
    {
//        search/$type?query=".urlencode($query)."&orderby=$orderBy&format=$format
        
        return parent::getEndpoint(); // TODO: Change the autogenerated stub
    }
}
